# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'frontend/webapp'
    output_location: 'dist'
    azure_static_web_apps_api_token: $(deployment_token)

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: '$(Build.SourcesDirectory)/backend/Farsight.Backend'
  displayName: 'Farsight.Backend - build'
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: '$(Build.SourcesDirectory)/backend/Farsight.IdentityService'
  displayName: 'Farsight.IdentityService - build'
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: '$(Build.SourcesDirectory)/backend/Farsight.CommonService'
  displayName: 'Farsight.CommonService - build'
